# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/sbin/cmake

# The command to remove a file.
RM = /usr/sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fish/Downloads/GithubProjects/GameEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fish/Downloads/GithubProjects/GameEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fish/Downloads/GithubProjects/GameEngine/CMakeFiles /home/fish/Downloads/GithubProjects/GameEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fish/Downloads/GithubProjects/GameEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runtime

# Build rule for target.
runtime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runtime
.PHONY : runtime

# fast build rule for target.
runtime/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/build
.PHONY : runtime/fast

#=============================================================================
# Target rules for targets named editor

# Build rule for target.
editor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 editor
.PHONY : editor

# fast build rule for target.
editor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/build
.PHONY : editor/fast

src/editor/main.o: src/editor/main.cpp.o
.PHONY : src/editor/main.o

# target to build an object file
src/editor/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/editor/main.cpp.o
.PHONY : src/editor/main.cpp.o

src/editor/main.i: src/editor/main.cpp.i
.PHONY : src/editor/main.i

# target to preprocess a source file
src/editor/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/editor/main.cpp.i
.PHONY : src/editor/main.cpp.i

src/editor/main.s: src/editor/main.cpp.s
.PHONY : src/editor/main.s

# target to generate assembly for a file
src/editor/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/editor/main.cpp.s
.PHONY : src/editor/main.cpp.s

src/render_backends/compatibility/core.o: src/render_backends/compatibility/core.cpp.o
.PHONY : src/render_backends/compatibility/core.o

# target to build an object file
src/render_backends/compatibility/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/render_backends/compatibility/core.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/render_backends/compatibility/core.cpp.o
.PHONY : src/render_backends/compatibility/core.cpp.o

src/render_backends/compatibility/core.i: src/render_backends/compatibility/core.cpp.i
.PHONY : src/render_backends/compatibility/core.i

# target to preprocess a source file
src/render_backends/compatibility/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/render_backends/compatibility/core.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/render_backends/compatibility/core.cpp.i
.PHONY : src/render_backends/compatibility/core.cpp.i

src/render_backends/compatibility/core.s: src/render_backends/compatibility/core.cpp.s
.PHONY : src/render_backends/compatibility/core.s

# target to generate assembly for a file
src/render_backends/compatibility/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/render_backends/compatibility/core.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/render_backends/compatibility/core.cpp.s
.PHONY : src/render_backends/compatibility/core.cpp.s

src/render_backends/progressive/core.o: src/render_backends/progressive/core.cpp.o
.PHONY : src/render_backends/progressive/core.o

# target to build an object file
src/render_backends/progressive/core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/render_backends/progressive/core.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/render_backends/progressive/core.cpp.o
.PHONY : src/render_backends/progressive/core.cpp.o

src/render_backends/progressive/core.i: src/render_backends/progressive/core.cpp.i
.PHONY : src/render_backends/progressive/core.i

# target to preprocess a source file
src/render_backends/progressive/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/render_backends/progressive/core.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/render_backends/progressive/core.cpp.i
.PHONY : src/render_backends/progressive/core.cpp.i

src/render_backends/progressive/core.s: src/render_backends/progressive/core.cpp.s
.PHONY : src/render_backends/progressive/core.s

# target to generate assembly for a file
src/render_backends/progressive/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/render_backends/progressive/core.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/render_backends/progressive/core.cpp.s
.PHONY : src/render_backends/progressive/core.cpp.s

src/runtime/main.o: src/runtime/main.cpp.o
.PHONY : src/runtime/main.o

# target to build an object file
src/runtime/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/runtime/main.cpp.o
.PHONY : src/runtime/main.cpp.o

src/runtime/main.i: src/runtime/main.cpp.i
.PHONY : src/runtime/main.i

# target to preprocess a source file
src/runtime/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/runtime/main.cpp.i
.PHONY : src/runtime/main.cpp.i

src/runtime/main.s: src/runtime/main.cpp.s
.PHONY : src/runtime/main.s

# target to generate assembly for a file
src/runtime/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runtime.dir/build.make CMakeFiles/runtime.dir/src/runtime/main.cpp.s
.PHONY : src/runtime/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... editor"
	@echo "... runtime"
	@echo "... src/editor/main.o"
	@echo "... src/editor/main.i"
	@echo "... src/editor/main.s"
	@echo "... src/render_backends/compatibility/core.o"
	@echo "... src/render_backends/compatibility/core.i"
	@echo "... src/render_backends/compatibility/core.s"
	@echo "... src/render_backends/progressive/core.o"
	@echo "... src/render_backends/progressive/core.i"
	@echo "... src/render_backends/progressive/core.s"
	@echo "... src/runtime/main.o"
	@echo "... src/runtime/main.i"
	@echo "... src/runtime/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

